import './partials/js/hero/hero';
import './partials/js/catalog/example';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import * as hero from './partials/js/hero/hero';
import * as catalog from './partials/js/catalog/example';
import * as header from './partials/js/header/header';
import * as upBtn from './partials/js/up-btn';
import * as clear from './partials/js/catalog/clearInput';
